language: dart
sudo: false
dart:
  - dev
cache:
  directories:
    - $HOME/.npm
    - $HOME/.nvm
    - $HOME/.pub-cache/hosted
    - $HOME/.chrome/canary
    - node_modules
before_install:
  - pub global activate dart_coveralls
  - export CHROME_CANARY_BIN=`./tool/get_chrome_canary.sh`
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install a recent node.js version through npm.
  - nvm install v4.0.0
  - export NODE_BIN=~/.nvm/versions/node/v4.0.0/bin/node
before_script:
  - npm install
script:
  - ./tool/presubmit.sh
